version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
    - ./frontend/src:/app/src

  backend:
    container_name: backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: news_tape
      PGDATA: /opt/pgsql/data
    ports:
      - "5432:5432"
    volumes:
      - /datadrive/pgdata:/opt/pgsql/data
    privileged: true

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  db-data:
    driver: local
